experiment:
  exp_dir: experiments/
  exp_name: ctb6

task: part-of-speech

dataset:
  data_dir: ${PATH_TO_DATASET}
  data_type: sequence_labeling
  data_format: column

preprocessor:
  type: sequence-labeling-preprocessor
  model_dir: babert-base
  max_length: 256
  bio2bioes: false

data_collator: SequenceLabelingDataCollatorWithPadding

model:
  type: sequence-labeling-model
  encoder:
    model_name_or_path: babert-base
  word_dropout: 0.1
  use_crf: true

trainer: ner-trainer

train:
  max_epochs: 20
  dataloader:
    batch_size_per_gpu: 32
  optimizer:
    type: AdamW
    lr: 5.0e-5
    param_groups:
      - regex: crf
        lr: 5.0e-1
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 20

evaluation:
  dataloader:
    batch_size_per_gpu: 128
  metrics:
    - type: ner-metric
    - type: ner-dumper
      model_type: sequence_labeling
      dump_format: column
